title: Stefan Barosan
logo: /assets/img/prof_pic.png
description: I am a Computer Science student with a keen interest in Machine Learning and Web Development
show_downloads: true
theme: jekyll-theme-minimal
